Add shared last event observer
alphatroya/KeyboardManager pull request #52
Opened 2021-06-02 13:56 UTC by Vladzzzzz

Добавил обсёрвер на текущее состояние клавиатуры.
Подобная проблема часто встречается на проектах

2021-06-04 10:18 UTC, alphatroya requested changes
Привет, хорошая работа, думаю это может пригодиться! Обдумав твой подход, я считаю что его можно немного улучшить.

Думаю, излишне добавлять поля в KeyboardObserver, это только нарушит SR принцип,  лучше использовать  отдельный объект. Думаю, существующий`LastKeyboardEventStorage` подойдет для этого. 
Предлагаю:
- перенести `LastKeyboardEventStorage` в отдельный файл
- сделать у него приватный инициализатор и публичное shared свойство (пусть будет синглтоном) 
- переместить lastEvent внутрь `LastKeyboardEventStorage`, пусть он будет единственным его публичным полем (кроме shared)
- содержимое `initEventObserver` переместить в init()
- в `deinit` удалять токен и отписываться от оповещений

2021-06-07 09:06 UTC, Vladzzzzz commented
Привет!
Есть два момента, которые хотел обсудить 

1) Инициализация 
Чтобы таймер стартовал, нужно обратиться к синглтону
Может быть стоит создать функцию а-ля initSharedInstance()? Для того чтобы не делать подобный вызов в апп делегаете
```
_ = LastKeyboardEventStorage.shared
```

2) NotificationCenter
В KeyboardObserver он передается во всех методах. Правильно ли тут решать за пользователя, какой nc использовать?
NС можно было бы передавать аргументом в initSharedInstance()

2021-06-07 09:15 UTC, alphatroya requested changes

2021-06-07 09:15 UTC, alphatroya commented on Sources/KeyboardManager/LastKeyboardEventStorage.swift
> +        shared.event
Здесь, очевидно, лучше возвращать event у self

2021-06-07 09:15 UTC, alphatroya commented on Sources/KeyboardManager/LastKeyboardEventStorage.swift
> +// Copyright (c) 2021 Alexey Korolev
Думаю, зря я сюда фамилию свою засунул. Можешь отредактировать `.swiftformat` файл и удалить там эту строчку и переформатировать все?

Заодно добавь свою фамилию в `README.md`

2021-06-07 09:15 UTC, alphatroya commented on Sources/KeyboardManager/LastKeyboardEventStorage.swift
> +public final class LastKeyboardEventStorage {
Можешь добавить комментарии с документацией для всех `public` полей?

Насчёт твоего комментария насчёт наиболее ранней инициализации, может нам просто упомянуть это в документации? Что `shared` надо инитить как можно раньше

После того как ты это сделаешь, можно вызвать make docs (перед этим установи https://github.com/SwiftDocOrg/swift-doc) чтобы он обновил документацию проекта. Она потом будет [здесь](https://alphatroya.github.io/KeyboardManager)

2021-06-07 09:15 UTC, alphatroya commented on Sources/KeyboardManager/LastKeyboardEventStorage.swift
> +    private init() {
> В KeyboardObserver он передается во всех методах. Правильно ли тут решать за пользователя, какой nc использовать? NС можно было бы передавать аргументом в initSharedInstance()

Подумал, про это. Не думаю что кто то будет сюда передавать какие то другие NC, но эта возможность может пригодиться в unit тестах. Думаю можно сделать init internal и добавить туда параметр (с дефолтным значением)

2021-06-08 10:10 UTC, alphatroya requested changes
Все ок, осталось только одно. Можешь написать пару тестов? В них нужно создавать LastKeyboardEventStorage (не shared) с notificationCenter, потом слать в него нотификации и проверять что lastEvent изменился. Плюс еще один тест кейз что отписка произошла. В текстах уже есть нужные хелперы, посмотри на их реализацию.

2021-06-17 10:40 UTC, alphatroya approved these changes

2021-06-17 10:59 UTC, merged

2021-06-17 11:03 UTC, alphatroya commented
Функционал доступен в версии 2.1